import type { Metadata } from 'next';

import { Header } from '@/components/Header';

import { robotoFont } from '@/font/robotoFont';

import '@/styles/app.css';
import { playwriteFont } from '@/font/playwriteFont';
import { AppProvider } from '@/provider/AppProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${playwriteFont.style} ${robotoFont.style}`}>
      <body>
        <AppProvider>
          <Header />
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
